### PR TITLE
Add ambiguous linting ability.

### LINKED ISSUE #32: Ability to lint no matter the scope.
Or rather, being able to create a linter that is able to be called no matter what scope the file loaded is.

This would be incredibly helpful for linters like linter-flint, and linter-gradle, that are generic directory based build tools.

### PR DESCRIPTION
**Pull request by k2b6s9j**
Just add a wildcard to your scopes array.
Fixes #32.

### CODE REVIEW

**Comment by AsaAyers** [comment]
Push modifies the array in place. Are you sure this doesn't run more than once?

**Comment by k2b6s9j** [comment]
I just added some logging code to my environment to check:

screen shot 2015-06-06 at 3 38 38 pm

Seems to be okay:

screen shot 2015-06-06 at 3 38 19 pm

**Comment by AsaAyers** [comment]
Ok, so that tells me that `editor.scopeDescriptorForBufferPosition` is returning a new object with a new `scopes` array every time. If it were returning the same one the fix would be

    scopes = scopes.concat(['*'])

I think either solution is fine for this situation. My personal preference is usually to write it more defensively using `concat`.

**Comment by k2b6s9j** [comment]
I'm down with whichever. I'm still pretty foreign to Node and CoffeeScript so whatever you think best.

**Comment by AsaAyers** [comment]
Since I'm curious I tracked it down and `editor.scopeDescriptorForBufferPosition` goes through a couple functions and ends up at [`new ScopeDescriptor(scopes: @tokenForPosition(position).scopes)`](https://github.com/atom/atom/blob/v0.201.0/src/tokenized-buffer.coffee#L379), so it's returning a new object every time.

There are too many tiny functions involved that just call out to other functions, I don't see exactly where the array comes from. Your test proves that it works, so I've lost interest in figuring this one out.

**Comment by steelbrain** [comment]
@AsaAyers Did you know that Function, Boolean, String, Integer they are all objects but special cased in Javascript. Maybe that object extends the array? or maybe it inherits the array push function and stores it's indices in the array format that make it array API compatible.

**Pull request merged**
