### PR TITLE
Fix invalid references

### PR DESCRIPTION
**Pull request by steelbrain**
Introduced by the recent naming conversion
These were the ones I found after a quick revision and run. I might've missed some.

### CODE REVIEW

**Comment by iam4x** [comment]
It was an hard job to digest, let's close this debate.

**Comment by hd-deman** [comment]
why `Type`, `File`, `HTML`, `Message` begins with a capital letter again?

**Comment by steelbrain** [comment]
Because they are a part of API and not a part of the code. and Because we don't want to break existing linters without a reason.

**Comment by AsaAyers** [comment]
Plugins are written in CoffeeScript/JavaScript and this change brings the API back in line with the most common convention of those languages. This causes less friction for plugin authors :+1:

**Comment by steelbrain** [comment]
Note: The changes I made in this PR are like javascript runtime error fixes, not art fixes.

**Pull request merged**
