### PR TITLE
Merged history from AtomLinterPlus/linter-plus

### PR DESCRIPTION
**Pull request by k2b6s9j**
I've merged the change history from the AtomLinterPlus repo into a branch here. There are no real changes, but it helps keep a continuous history.

### CODE REVIEW

**Comment by steelbrain** [comment]
The diff shows 0 files changed.

**Comment by k2b6s9j** [comment]
Yes. This pull request isn't about changed files, it's to keep history. The files those commits changed conflicted with the information currently in this repo.

**Comment by steelbrain** [comment]
Oh, in that case. LGTM

**Comment by AsaAyers** [comment]
With 0 files changed I just don't see the point. It just pollutes the history with changes we don't need long term. If you want a place to see the name flip back and forth go look at https://github.com/AtomLinter/linter-plus/commit/d80be37b8a8c70995bf08f721f890e79c6c7e4af and then https://github.com/AtomLinter/linter-plus/commit/89d4fbdc6b3596bca4a242eadb7fdbdcaa58d394

If anyone can come up with a reason we _do_ need to make this change it's fine to re-open, but I'm opposed to changes just because we can.

**Pull request closed without merging**
